site_name: ISPP 18
pages:
- Inicio: 'index.md'
- Feedback:
    - 'General': 'feedbacks/general/feedbacks.md'
    - 'Presentación': 'feedbacks/general/presentacion.md'
    - 'Contenido': 'feedbacks/general/contenido.md'
    - 'Negocio': 'feedbacks/general/negocio.md'
    - 'Estilo': 'feedbacks/general/estilo.md'
- Adrenalive: 
    - 'Clase 1': 'feedbacks/adrenalive/clase1.md'
    - 'Clase 2': 'feedbacks/adrenalive/clase2.md'
    - 'Clase 3': 'feedbacks/adrenalive/clase3.md'
    - 'Clase 4': 'feedbacks/adrenalive/clase4.md'
    - 'Clase 5': 'feedbacks/adrenalive/clase5.md'
    - 'Clase 6': 'feedbacks/adrenalive/clase6.md'
    - 'Clase 7': 'feedbacks/adrenalive/clase7.md'
    - 'Clase 8': 'feedbacks/adrenalive/clase8.md'
    - 'Clase 9': 'feedbacks/adrenalive/clase9.md'
    - 'Clase 10': 'feedbacks/adrenalive/clase10.md'
- InteracTeach: 
    - 'Clase 1': 'feedbacks/climbcode/clase1.md'
    - 'Clase 2': 'feedbacks/climbcode/clase2.md'
    - 'Clase 3': 'feedbacks/climbcode/clase3.md'
    - 'Clase 4': 'feedbacks/climbcode/clase4.md'
    - 'Clase 5': 'feedbacks/climbcode/clase5.md'
    - 'Clase 6': 'feedbacks/climbcode/clase6.md'
    - 'Clase 7': 'feedbacks/climbcode/clase7.md'
    - 'Clase 8': 'feedbacks/climbcode/clase8.md'
    - 'Clase 9': 'feedbacks/climbcode/clase9.md'
    - 'Clase 10': 'feedbacks/climbcode/clase10.md'
    - 'Clase 11': 'feedbacks/climbcode/clase11.md'
    - 'Clase 12': 'feedbacks/climbcode/clase12.md'
- Cocome: 
    - 'Clase 1': 'feedbacks/cocome/clase1.md'
    - 'Clase 2': 'feedbacks/cocome/clase2.md'
    - 'Clase 3': 'feedbacks/cocome/clase3.md'
    - 'Clase 4': 'feedbacks/cocome/clase4.md'
    - 'Clase 5': 'feedbacks/cocome/clase5.md'
    - 'Clase 6': 'feedbacks/cocome/clase6.md'
    - 'Clase 7': 'feedbacks/cocome/clase7.md'
    - 'Clase 8': 'feedbacks/cocome/clase8.md'
    - 'Clase 9': 'feedbacks/cocome/clase9.md'
    - 'Clase 10': 'feedbacks/cocome/clase10.md'
    - 'Clase 11': 'feedbacks/cocome/clase11.md'
    - 'Clase 12': 'feedbacks/cocome/clase12.md'
- Drafter: 
    - 'Clase 1': 'feedbacks/drafter/clase1.md'
    - 'Clase 2': 'feedbacks/drafter/clase2.md'
    - 'Clase 3': 'feedbacks/drafter/clase3.md'
    - 'Clase 4': 'feedbacks/drafter/clase4.md'
    - 'Clase 5': 'feedbacks/drafter/clase5.md'
    - 'Clase 6': 'feedbacks/drafter/clase6.md'
    - 'Clase 7': 'feedbacks/drafter/clase7.md'
    - 'Clase 8': 'feedbacks/drafter/clase8.md'
    - 'Clase 9': 'feedbacks/drafter/clase9.md'
    - 'Clase 10': 'feedbacks/drafter/clase10.md'
- Makai: 
    - 'Clase 1': 'feedbacks/makai/clase1.md'
    - 'Clase 2': 'feedbacks/makai/clase2.md'
    - 'Clase 3': 'feedbacks/makai/clase3.md'
    - 'Clase 4': 'feedbacks/makai/clase4.md'
    - 'Clase 5': 'feedbacks/makai/clase5.md'
    - 'Clase 6': 'feedbacks/makai/clase6.md'
    - 'Clase 7': 'feedbacks/makai/clase7.md'
    - 'Clase 8': 'feedbacks/makai/clase8.md'
    - 'Clase 9': 'feedbacks/makai/clase9.md'
    - 'Clase 10': 'feedbacks/makai/clase10.md'
    - 'Clase 12': 'feedbacks/makai/clase12.md'
- Traveliers: 
    - 'Clase 1': 'feedbacks/traveliers/clase1.md'
    - 'Clase 2': 'feedbacks/traveliers/clase2.md'
    - 'Clase 3': 'feedbacks/traveliers/clase3.md'
- Quickademy:
    - 'Clase 1': 'feedbacks/quickademy/clase1.md'
    - 'Clase 2': 'feedbacks/quickademy/clase2.md'
    - 'Clase 3': 'feedbacks/quickademy/clase3.md'
- Weris/QRico: 
    - 'Clase 1': 'feedbacks/weris/clase1.md'
    - 'Clase 2': 'feedbacks/weris/clase2.md'
    - 'Clase 3': 'feedbacks/weris/clase3.md'
    - 'Clase 4': 'feedbacks/weris/clase4.md'
    - 'Clase 5': 'feedbacks/weris/clase5.md'
    - 'Clase 6': 'feedbacks/weris/clase6.md'
    - 'Clase 7': 'feedbacks/weris/clase7.md'
   
- Subir wiki: 'tutorial_subida.md'
theme:
    name: 'material'
markdown_extensions:
- toc:
permalink: True
