site_name: ISPP 18
pages:
- Inicio: 'index.md'
- Feedback:
    - 'General': 'feedbacks/general/feedbacks.md'
    - 'Presentación': 'feedbacks/general/presentacion.md'
    - 'Contenido': 'feedbacks/general/contenido.md'
    - 'Negocio': 'feedbacks/general/negocio.md'
    - 'Estilo': 'feedbacks/general/estilo.md'
- Adrenalive: 
    - 'Clase 1': 'feedbacks/adrenalive/clase1.md'
    - 'Clase 2': 'feedbacks/adrenalive/clase2.md'
    - 'Clase 3': 'feedbacks/adrenalive/clase3.md'
    - 'Clase 4': 'feedbacks/adrenalive/clase4.md'
- ClimbCode: 
    - 'Clase 1': 'feedbacks/climbcode/clase1.md'
    - 'Clase 2': 'feedbacks/climbcode/clase2.md'
    - 'Clase 3': 'feedbacks/climbcode/clase3.md'
    - 'Clase 4': 'feedbacks/climbcode/clase4.md'
    - 'Clase 5': 'feedbacks/climbcode/clase5.md'
- Cocome: 
    - 'Clase 1': 'feedbacks/cocome/clase1.md'
    - 'Clase 2': 'feedbacks/cocome/clase2.md'
- Drafter: 
    - 'Clase 1': 'feedbacks/drafter/clase1.md'
- Makai: 
    - 'Clase 1': 'feedbacks/makai/clase1.md'
    - 'Clase 2': 'feedbacks/makai/clase2.md'
    - 'Clase 3': 'feedbacks/makai/clase3.md'
    - 'Clase 4': 'feedbacks/makai/clase4.md'
- Traveliers: 
    - 'Clase 1': 'feedbacks/traveliers/clase1.md'
    - 'Clase 2': 'feedbacks/traveliers/clase2.md'
    - 'Clase 3': 'feedbacks/traveliers/clase3.md'
- Quickademy:
    - 'Clase 1': 'feedbacks/quickademy/clase1.md'
    - 'Clase 2': 'feedbacks/quickademy/clase2.md'
    - 'Clase 3': 'feedbacks/quickademy/clase3.md'
- Weris/QRico: 
    - 'Clase 1': 'feedbacks/weris/clase1.md'
    - 'Clase 2': 'feedbacks/weris/clase2.md'
    - 'Clase 3': 'feedbacks/weris/clase3.md'
    - 'Clase 4': 'feedbacks/weris/clase4.md'
- Subir wiki: 'tutorial_subida.md'
theme:
    name: 'material'
markdown_extensions:
- toc:
    permalink: True
